defaults: &defaults
  working_directory: /go/src/github.com/SpectoLabs/hoverfly
  docker:
    - image: spectolabs/golang:1.8.3
  environment:
    - GOPATH: /go

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test

  build-docker:
    <<: *defaults
    steps:
      - run:
          name: Run tests
          command: docker build -t spectolabs/hoverfly:$CIRCLE_BUILD_NUM  -f /go/src/github.com/SpectoLabs/hoverfly/core/Dockerfile .

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - build-docker:
          requires:
            - build